### PR TITLE
Fix continuously obtaining of the refresh tokens

### LINKED ISSUE #19: Refresh tokens is broken
`Yoast_Google_Analytics_Client->refresh_tokens()` attempts to [get response via `$response = $this->refreshToken( $refresh_token );`](https://github.com/Yoast/api-libs/blob/594cd038a38f67933fb861433e77ddf3b4c951be/googleanalytics/class-google-analytics-client.php#L74), which is void return method.

I am not confident in what should this be adjusted to?

Likely cause for recurrent HTTP requests, see https://github.com/Yoast/google-analytics-for-wordpress/issues/261

### PR DESCRIPTION
**Pull request by andizer**
Fixes #19 

The refresh tokens will be renewed all the time, but this isn't necessary. This fix contains the addition of storing the access token and validation of the expiration of that access token. This means the refresh tokens aren't obtained every page request, but only after access token is expired.

This pull has some consequences for the Google Analytics API implementation for the GA plugin and for the Google Search Console API implementation for the WP SEO plugin. Be sure the pull for GA is merged also to prevent issues.

### CODE REVIEW

**Comment by andizer** [comment]
@Rarst Can you review this pull request to see if this will fix issue #19

File: google/class-api-google-client.php [hunk 1]
```diff
@@ -0,0 +1,264 @@
...
+	 * @var string
+	 */
+	protected $http_response_code;
+
+	/**
+	 * Initialize the config and refresh the token
+	 *
+	 * @param array $config
+	 */
+	public function __construct( $config ) {
```
Comment (omarreiss) [inline google/class-api-google-client.php]: Also pass in an option prefix so you don't need children objects

Comment (omarreiss) [inline google/class-api-google-client.php]: api url too

**Comment by omarreiss** [comment]
CR 1 done

File: google/class-api-google-client.php [hunk 2]
```diff
@@ -0,0 +1,264 @@
...
+
+	/**
+	 * Doing a request to the API
+	 *
+	 * @param string $target_request_url
+	 * @param string $request_method
+	 *
+	 * @return array
+	 */
+	public function do_request( $target_request_url, $request_method = 'GET' ) {
```
Comment (omarreiss) [inline google/class-api-google-client.php]: please add a param `decode` (default false) so we can decode the response here instead of tons of other places where this is used.

**Comment by andizer** [comment]
This one is ready for another codereview @omarreiss

**Comment by Rarst** [comment]
Sorry I hadn't got to it before merge, still have a large pile of issues to go through after WCEU. :) Will let you know if I notice any more errant requests.
